version: 0.4.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release
platform: Any CPU
build_script:
- cmd: build.cmd
test: off
artifacts:
  - path: 'Solution\Artifacts\Packages\*.nupkg'
    name: MichonnePackages
assembly_info:
  patch: true
  file: version.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
