version: 0.5.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release
platform: Any CPU
build_script:
  - cmd: Nightly.cmd
build:
  verbosity: minimal
test: off

environment:
  MICHONNE_NUGET_API_KEY: ad9c47dd-d3b9-4962-9df5-13eff5b1032f

deploy:
- provider: NuGet
  api_key:
    secure: 29tN7eFt0JJe5i9QlGyiy/30MnnH1tJOOPkFrNUUdnEG1p2KlVTAbigZ69bAXwLX

assembly_info:
  patch: true
  file: version.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
